<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UserManagementTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-07-26T19:08:32</lastRun>
   <mailRecipient>vijay.n@genpact.com;</mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>15</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>d97fc378-28a2-413f-bc5e-5abb2ef970ff</testSuiteGuid>
   <testCaseLink>
      <guid>5e5ff229-730c-4078-a056-d91ae68f8edf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/Login/Invalid_Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec1145e7-0f0d-47cc-bdee-3c2b5f65ebab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f678e941-3a15-4100-b0d2-25ef4370cd3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37e6fcea-345a-49d4-9345-b9c946acca34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41b7ac21-fd23-4f43-b75b-031cf1030947</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0c67af0-977d-47b4-8053-835f16fdd50e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/Login/Valid_Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8270e857-7a2d-4223-b38e-d431b8611344</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a56ad12f-3c42-4ab1-8705-c7a00e20169e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd2e67d9-31ca-4485-b57d-20e969bcf34b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c111d1-3f7a-4e37-8770-04865c31318f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fc89f38-c784-424b-bf94-99c15dc9c873</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fcf86c13-b28d-476a-a54c-34e92a4de961</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/CreateUser/Create_User_Validate</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28317e29-6f8b-4eb8-9987-957eafd2f470</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c445c9cd-c45c-4e29-b3b4-03f8209f25cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d949b7a-d808-426c-afd7-5238d2a92dda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aca7fce-dfac-40b1-a953-7cc1cb1e6dd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66d28acc-7737-4552-80e8-1f251fc639a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10abd309-093a-4ed0-947f-fe3db947cb5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddc87b6d-a60a-4a6f-8b2b-3aa97856a5a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>903ec8d6-0ec4-496a-b294-12a35b9c5159</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>655e685b-2de2-45ff-a177-ef0304b6c405</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/CreateUser/Verify_InValid_Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64287bb8-5f16-4041-a66d-fb6059a86b22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe5201f-c4f5-4b27-a798-1248c499170e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eb0dd3b-165e-45ca-ac46-6ef60ea63454</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5a233b6-ba28-4b9b-9320-d9056171b179</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb9c9e8d-0e63-4851-83d9-21bc19d12ea2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/CreateUser/Verify_SaveExit_Btn</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9e2ef70-ff0b-40ba-9ce5-6b7f185e56a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d9c0d25-7136-4ab5-b7b2-f1a12d60af87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc401760-261d-497d-9650-99dc1560fb21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e210aff-cd54-4e46-b9b3-000c701e6336</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ea2b44-028b-4416-8864-7d9b0e7e4a79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01ea5b77-d8f0-44de-a036-e92f977a3fc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d5eb85b-eda7-4d70-805a-04f587dce7f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eff998a7-303d-442d-a1e5-7f3f5330ea80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/CreateUser/Verifying_Duplicate_EmailID</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb143e8e-1256-40a6-876b-62b40c870725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e95ca2bb-b711-474e-a1a6-3398f28fc62e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7e2d380-0848-4539-b8fd-bf46f9f7d473</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84be62cc-a768-4bba-b73b-100b5c50ae82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a89d3026-e50a-4882-98ef-2035d2a0e50c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49478fcc-d48b-4918-9d27-0e940df1239b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0487910-4fae-4822-aa7f-fb3e196d756d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Activate_User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40494071-2405-4a9e-93fd-a603de87468f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0854ca44-1d3c-4aa0-a250-23ed77cd11c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a411139b-c599-4c92-8f10-d3a72fa50730</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75cf68fd-9593-46ed-ba20-b597d448e9af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>339e2054-d55e-426c-a8e3-4f5880afe29c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2c92531-3fc9-4b6b-9618-1e824d412619</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>245be288-2204-4413-880f-bd531ff8fa68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4532b551-a798-4724-978d-8238baf0cdce</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/Login/LogoutAndCloseBrowser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ccfcb6f-4ba9-4a70-84de-01c26caa6339</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Verify_RoleChange</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce6e8187-8ddd-42aa-8c5e-a59b965b20df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f51a779f-7333-443d-92d5-61685e2a53d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c4309f7-0524-4bf1-ba0f-4e67e092e187</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>453b22a2-71e3-4dce-9e9b-633a606c5f44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c587718-b1fd-4b84-95ed-6e776c468547</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>203ff935-61d4-4df1-9b32-568f8f68d657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d03cbfc-1ac1-4044-a783-e348c958e837</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ca5fab-a80b-478a-9a09-03d843917d7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c528d3d2-1a12-45fe-b198-3a6abb661779</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Verify_AdvanceFilterPopUp</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a0ac4a0e-6d41-47fc-a739-8e00e60107fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/VerifyNextButtonClickNotAllowed</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7bfac0a7-87ff-435a-8569-c09d73b19e78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/VerifyDefaultSelectionAdvancedFilter</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e5c2d4b9-d1cb-4851-b265-305082918d2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Validate_User_Search</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb3b8859-7295-4785-b9b7-e251b7227cb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>391a4c0b-59b2-424c-a085-9baaafadd7c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09a2dbc2-0d28-4325-bc59-d76afd0e83a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Validate_Search_EmailID</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>679cf695-1db3-4c9f-9904-8fd232d4f135</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79fff897-f422-46d6-88f7-850a36e5e1f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caecf686-2384-48b4-be36-91bfea868124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdae5627-ec98-4a51-822f-35d2d2bbf704</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad40e780-8bb5-472a-9cbc-e893cf95ae7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1bc5592-3cd8-466d-8ac1-71b1b78f15b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139c301f-7e95-4dac-bed9-07f0cfef1c08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f23f55c1-8624-4231-86de-f14a94a31ff7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42069e28-87d8-45f8-96bc-7f5ae28040c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5221e16b-6611-4fb1-8963-f93cd9f9c3f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Validate_RoleBasedOnFilter</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0fcdf46-8472-47b3-9519-4d8b43ae52a5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d41e9ff3-67a3-4440-8f7e-4197026a61ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/VerifyErrorMessageDialogBox</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b89d199-f0c4-42eb-93fe-ce11ee96c5e2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e82216e6-895c-4023-8bb7-ea2b931f2b02</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Validate_Cancel_Of_CreateUsers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b319b5-39b7-43f3-868c-522a75e69f01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b31f6a-5354-4693-abc7-70c2758913ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55e0c2cc-5d5d-4984-af2e-bf3e89bf36c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ca7aa47-2fce-4227-b6c9-99715bdc1c0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>247bc6a7-42ca-42e2-bb97-0469cc007d1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e70060e-eed7-462c-9ab8-eb9ccd6b60d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ea052f7-07da-48ab-a538-76d8519c6a89</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd91817c-8ede-4802-800b-078ae3605b54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Validate_ModifyDataFromEdituser</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8034753-c182-47cc-9435-ef7a44e5dcc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1197c784-9941-4920-a788-82dd9cb57205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf9b6673-2e32-4338-8fae-1ecf49278686</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f74217e1-24f8-4bef-9521-837b1687026f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dafc0915-7e2e-4149-a212-f8bf525001de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51487f29-bdfe-4f82-aedd-6910225ee2d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b21016-0c8a-44cd-83d9-089088900bce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd552f5-ee3b-41b0-b415-0e896ef997f0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2b391b0-4132-49ad-8914-25340ef4f988</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/DeActivate_User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1fc8dc7-f5c0-4954-a381-45882bdece96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc88058b-2fc0-4ef6-b375-50a0d2bcf248</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e32298b0-5ad9-4cc7-8c53-1c55da7f8f19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31fb059f-aef1-40bb-9017-4cf5838aa258</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe0730f-144d-4fc1-8f70-4b72272ead24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d655a27-6889-45e5-b2df-0f688bdb8bee</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>871fa13e-237b-454b-8a3b-7d00d67a6e74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/LockUser</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>03fec3f4-231d-42a9-b6f4-f7f27493bf12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/UserManagementTestCases/UserActions/Unlock_User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32f9b483-b522-4d42-97a3-84ed181105be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0edd17f4-d7b8-40c2-b815-980e7ccedab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7aafbe3-2735-4992-8db5-3dd7b4bdac83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b56953f-a193-4721-84e6-229ba2ca9795</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50a45d17-4e08-4b5c-84ed-c10e60dac4bf</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
