<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Locked_Icon</name>
   <tag></tag>
   <elementGuidId>e45297d5-e497-434c-8a11-1a5f0f886ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//tr[contains(text(),'Lock')]/ancestor::td/following-sibling::td/descendant::span[@class='locked-status-locked'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
