<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logout_link</name>
   <tag></tag>
   <elementGuidId>43f862ac-09c0-4be2-be52-edb43036bc44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[text()='Logout']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[(text() = 'Logout' or . = 'Logout')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logout_menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainDiv&quot;)/headercomponents[1]/header[@class=&quot;navbar navbar-default navbar-fixed-top top_header&quot;]/div[@class=&quot;col-md-5 col-xs-8 hidden-xs&quot;]/ul[@class=&quot;nav navbar-nav navbar-right header-menu&quot;]/li[2]/div[@class=&quot;profile user-options open&quot;]/ul[@class=&quot;logout_container dropdown-menu&quot;]/li[1]/a[@class=&quot;logout_menu&quot;]</value>
   </webElementProperties>
</WebElementEntity>
