<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>material_list</name>
   <tag></tag>
   <elementGuidId>ed0c4cda-1033-4d3f-b124-2c5a5e06ef09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//h2)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
