<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EditUserFirstName</name>
   <tag></tag>
   <elementGuidId>8c513fb2-56c8-4bd0-9570-7e0f670765c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//INPUT[@id='firstName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
