<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>History_TotalRescueQuantity</name>
   <tag></tag>
   <elementGuidId>a6cf7c43-2b5b-4a56-8a34-63627727cb25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='filterPanelForHistory']/preceding::tr/td[starts-with(text(),'Total')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
