<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//INPUT[@id='lastName']</description>
   <name>lastName_Field</name>
   <tag></tag>
   <elementGuidId>abd2a826-e05b-43bb-b60f-2940cc42acd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//INPUT[@id='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
