<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_AllCustomer_Checkbox</name>
   <tag></tag>
   <elementGuidId>199c0e4b-dd27-4f99-a86c-0eb917f943c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//label[text()='Watsons']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
