<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SSM_Checkbox</name>
   <tag></tag>
   <elementGuidId>6232cfdd-f5df-4f92-a258-40c59475957e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//label[text()=&quot;SSM&quot;]/preceding::input[@type=&quot;checkbox&quot;][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
